#!/usr/bin/env bash

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER app
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

# Установка прав на volume
chown -R app:app /var/www/html
chmod -R 775 /var/www/html/storage

exec gosu app supervisord -c /etc/supervisor/conf.d/supervisord.conf

#if [ $# -gt 0 ]; then
#    exec gosu $WWWUSER "$@"
#else
#    # Проверка прав для Supervisor
#    chown -R app:app /var/log/supervisor /var/run/supervisor
#    exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
#fi
