[supervisord]
user=app
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisor/supervisord.pid

[program:php]
user=app
command=%(ENV_SUPERVISOR_PHP_COMMAND)s
directory=/var/www/html
environment=
    HOME="/home/app",
    USER="app"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:laravel-worker]
user=app
command=php /var/www/html/artisan queue:work
directory=/var/www/html
environment=
    HOME="/home/app",
    USER="app"
process_name=%(program_name)s_%(process_num)02d
autostart=true
autorestart=true
numprocs=8
redirect_stderr=true
stdout_logfile=/var/www/html/storage/logs/worker.log

# [unix_http_server]
# file=/var/run/supervisor.sock  ; (the path to the socket file)
# chmod=0700                     ; socket file mode (default 0700)
# chown=root:root                ; socket file uid:gid owner
